### ISSUE TITLE
Where are the chickens?

### ISSUE THREAD

**Issue by smutek** [mimikim/The-Chicken-Game#1]
I was going to check this out but can’t find the chickens, just the readme. Is this one in CodePen? More so, saying hi. Hope you’re doing okay. - Jimmy

**Comment by smutek** [comment]
Resolved! I mainly just wanted to say hi. Hi! :)

**Comment by mimikim** [comment]
hey @smutek ! The code for this isn't up yet but I am hoping to make it into a game with Phaser 3
